<?php

/**
 * @file
 * Provides a aktualnosci_kategorie entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\aktualnosci_kategorie\Entity\aktualnosci_kategorie;
use Drupal\user\UserInterface;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

function aktualnosci_kategorie_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {


  // if ($operation == 'view' && $account->hasPermission('aktualnosci_kategorie.view')) {
  //   return AccessResult::allowed();
  // } elseif (in_array($operation, ['delete', 'edit', 'update']) && $account->hasPermission('aktualnosci_kategorie.edit')) {
  //   return AccessResult::allowed();
  // }
  // return AccessResult::forbidden();

  return AccessResult::allowed();
}

function aktualnosci_kategorie_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  // Sprawdź, czy tworzona jednostka jest jednostką, którą chcesz śledzić.
  if ($entity->getEntityTypeId() == 'aktualnosci_kategorie') {
    // Skonfiguruj ścieżkę docelową przekierowania.
    $path = '/admin/content/kategorie-aktualnosci';
    // Przygotuj odpowiedź przekierowania.
    $response = new RedirectResponse($path);
    // Wykonaj przekierowanie.
    $response->send();
  }
}

/**
 * Implements hook_theme().
 */
function aktualnosci_kategorie_theme() {

  return [
    'aktualnosci_kategorie' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for aktualnosci_kategorie templates.
 *
 * Default template: aktualnosci_kategorie.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the aktualnosci_kategorie information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_aktualnosci_kategorie(array &$variables) {

  $variables['view_mode'] = $variables['elements']['#view_mode'];


  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
// function aktualnosci_kategorie_user_cancel($edit, UserInterface $account, $method) {
//   switch ($method) {
//     case 'user_cancel_block_unpublish':
//       // Unpublish aktualnosci_kategories.
//       $storage = \Drupal::entityTypeManager()->getStorage('aktualnosci_kategorie');
//       $aktualnosci_kategorie_ids = $storage->getQuery()
//         ->condition('uid', $account->id())
//         ->condition('status', 1)
//         ->execute();
//       foreach ($storage->loadMultiple($aktualnosci_kategorie_ids) as $aktualnosci_kategorie) {
//         $aktualnosci_kategorie->set('status', FALSE);
//         $aktualnosci_kategorie->save();
//       }
//       break;

//     case 'user_cancel_reassign':
//       // Anonymize aktualnosci_kategories.
//       $storage = \Drupal::entityTypeManager()->getStorage('aktualnosci_kategorie');
//       $aktualnosci_kategorie_ids = $storage->getQuery()
//         ->condition('uid', $account->id())
//         ->execute();
//       foreach ($storage->loadMultiple($aktualnosci_kategorie_ids) as $aktualnosci_kategorie) {
//         $aktualnosci_kategorie->setOwnerId(0);
//         $aktualnosci_kategorie->save();
//       }
//       break;
//   }
// }

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
// function aktualnosci_kategorie_user_predelete(UserInterface $account) {
//   // Delete aktualnosci_kategories.
//   $storage = \Drupal::entityTypeManager()->getStorage('aktualnosci_kategorie');
//   $aktualnosci_kategorie_ids = $storage->getQuery()
//     ->condition('uid', $account->id())
//     ->execute();
//   $aktualnosci_kategories = $storage->loadMultiple($aktualnosci_kategorie_ids);
//   $storage->delete($aktualnosci_kategories);
//   // Delete old revisions.
//   $aktualnosci_kategorie_ids = $storage->getQuery()
//     ->allRevisions()
//     ->condition('uid', $account->id())
//     ->execute();
//   foreach (array_keys($aktualnosci_kategorie_ids) as $revision_id) {
//     $storage->deleteRevision($revision_id);
//   }
// }
