# Schema for the configuration files of the Freshmail Integration CG2 module.
freshmail_integration_cg2.settings:
  type: config_object
  label: 'Freshmail Integration CG2 settings'
  mapping:
    example:
      type: string
      label: 'Example'
